imports:
    - { resource: 'easy_admin/' }

parameters:
    # exclude globally, if not explicitly listed
    easy_admin_exclude_fields: ['createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'trainingFeedbacks', 'trainingTerms', 'registrations', 'trainings', 'slug', 'isProvisionPaid', 'uploadDestination', 'relativeUploadDestination', 'marketingEvents', 'expenses']

easy_admin:
    site_name: "Trainings from Péhápkaři Community"

    # https://symfony.com/doc/master/bundles/EasyAdminBundle/book/list-search-show-configuration.html#customizing-date-and-time-properties
    formats:
        # czech format
        date: 'j. n. Y'
        time: 'H:i'
        datetime: 'j. n. Y, H:i'

    list:
        actions:
            # see: https://symfony.com/doc/master/bundles/EasyAdminBundle/book/actions-configuration.html#removing-action-labels-and-displaying-just-icons
            -
                name: 'edit'
                icon: 'pencil'
                label: false
                css_class: 'btn btn-sm btn-light pl-2'
            -
                name: 'delete'
                icon: 'times'
                label: false
                css_class: 'btn btn-sm btn-danger pl-2'
