security:
    access_denied_url: /access-denied

    access_control:
        # allow access to "/admin" only to logged-in
        -
            path: '^/admin'
            roles: ROLE_ADMIN

    encoders:
        Pehapkari\User\Entity\User: 'argon2i'

    providers:
        # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
        app_user_provider:
            entity:
                class: 'Pehapkari\User\Entity\User'
                property: 'name'

    # https://symfony.com/doc/current/security.html#initial-security-yml-setup-authentication
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # this firewall applies to all URLs
            pattern: ^/

            # but the firewall does not require login on every page
            # denying access is done in access_control or in your controllers
            anonymous: true

            # This allows the user to login by submitting a username and password
            # Reference: https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                # The route name that the login form submits to
                check_path: "login"
                # The name of the route where the login form lives
                # When the user tries to access a protected page, they are redirected here
                login_path: "login"
                # Secure the login form against CSRF
                # Reference: https://symfony.com/doc/current/security/csrf_in_login_form.html
                csrf_token_generator: security.csrf.token_manager
                # The page users are redirect to when there is no previous page stored in the
                # session (for example when the users access directly to the login page).
                default_target_path:  "login"

            logout:
                # The route name the user can go to in order to logout
                path: "logout"
                # The name of the route to redirect to after logging out
                target: homepage

            guard:
                authenticators:
                    - Pehapkari\User\Security\PehapkariAuthenticator
