twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '_snippets/form/layout.twig'
        - '_snippets/form/fields.twig'

    globals:
        training_max_references_to_show: '%training_max_references_to_show%'
        image_uploads: '%image_uploads%'

    # see https://symfony.com/blog/new-in-symfony-2-7-default-date-and-number-format-configuration
    date:
        format: 'j. n., g:i' # Czech format

    # see https://symfony.com/blog/new-in-symfony-2-7-default-date-and-number-format-configuration
    number_format:
        decimals: 0
        decimal_point: ','
        thousands_separator: ' '
