os: linux
language: php
php: 7.3

before_install:
    # turn off XDebug to speed up
    - phpenv config-rm xdebug.ini || return 0

install:
    - composer install --no-progress

jobs:
    include:
        # 1. Building Docker image, testing & static analysis
        -
            # for faster CI, this runs in parallel with testing and static analysis
            stage: test
            name: 'Build Docker Image'
            if: NOT type = cron
            install:
                - echo "composer install is run inside the Docker image"
            script:
                - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                - docker pull pehapkari/pehapkari.cz || true
                - docker build --cache-from pehapkari/pehapkari.cz -t pehapkari/pehapkari.cz:$TRAVIS_COMMIT --target production -f Dockerfile .
                - docker push pehapkari/pehapkari.cz

        -
            stage: test
            name: ECS
            script:
                - composer check-cs

        -
            name: PHPStan
            script:
                - composer phpstan

        -
            name: PHPUnit
            script:
                - vendor/bin/phpunit

        -
            name: Rector
            script:
                - composer rector-dry

        -
            name: 'Symfony Linting'
            script:
                - bin/console lint:yaml src packages
                - bin/console lint:twig packages templates

        # 2. Build Docker image â†’ deploy
        -
            stage: warmup
            name: 'Production Cache Warmup'
            install:
                - echo "composer install is run inside the Docker image"
            script:
                - docker run --rm -e APP_ENV=prod pehapkari/pehapkari.cz:$TRAVIS_COMMIT bin/console cache:warmup

        -
            stage: deploy
            name: 'Deploy to pehapkari.cz'
            install:
                - echo "composer install is run inside the Docker image"
            if: branch = master AND type = push
            script: skip
            deploy:
                -
                    provider: script
                    script: sh bin/deploy.sh
                    skip_cleanup: true

#        -
#            stage: crons
#            name: 'Tweet Post'
#            if: branch = master
#            script:
#                - vendor/bin/statie tweet-post statie/source

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
