easy_admin:
    entities:
        Feedback:
            class: 'Pehapkari\Training\Entity\TrainingFeedback'
            list:
                # see https://symfony.com/doc/master/bundles/EasyAdminBundle/book/list-search-show-configuration.html#static-filters-dql-filter-option
                sort: 'isRevised'
                fields: &feedbackFields
                    - 'isRevised'
                    - 'name'
                    - 'text'
                    - { property: 'text', template: 'snippet/admin/full_text.twig' }
                    - { property: 'rating', label: 'Rating' }
                    - 'training'
                    - { property: 'isShownOnMainPage', label: 'Main Page' }
                    - 'isPublic'
