imports:
    - { resource: "easy_admin.yaml" }

services:
    _defaults:
        public: true
        autowire: true

    OpenRealEstate\PriceMap\:
        resource: '../src'
        exclude: '../src/{Entity,Form}'

    PhpOffice\PhpSpreadsheet\Reader\Xls:
        calls:
            # better performance
            - ['setReadDataOnly', [true]]
