services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Pehapkari\Blog\:
        resource: '../src'

    # for rendering markdown posts
    ParsedownExtra:
        class: 'ParsedownExtra'

    Symplify\Statie\Generator\Generator:
        factory: ['@Pehapkari\Blog\DependencyInjection\StatieFactory', 'createGenerator']

    Symplify\Statie\Generator\RelatedItemsResolver:
        factory: ['@Pehapkari\Blog\DependencyInjection\StatieFactory', 'createRelatedItemsResolver']
