services:
    _defaults:
        autowire: true
        public: true

    Pehapkari\Provision\:
        resource: '../src'
        exclude:
            '../src/Entity/*'
            '../src/Data/*'
            '../src/ValueObject/*'
