easy_admin:
    design:
        brand_color: '#00A8C6'
        assets:
            # https://symfony.com/doc/master/bundles/EasyAdminBundle/book/design-configuration.html#loading-the-entire-bootstrap-framework
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
                - 'assets/css/custom_backend.css'

        menu:
            # see https://symfony.com/doc/master/bundles/EasyAdminBundle/book/menu-configuration.html#menu-dividers
            -
                label: 'Training Term'

            -
                label: 'Training Terms'
                icon: 'calendar'
                entity: 'TrainingTerm'
            -
                icon: 'id-badge'
                entity: 'Registration'
            -
                label: 'Expenses'
                icon: 'money'
                entity: 'Expense'
            -
                label: 'Generate Certificate'
                icon: 'plus'
                route: 'create_certificate'

            -
                label: 'Website Content'

            -
                label: 'Trainings'
                icon: 'graduation-cap'
                entity: 'Training'

            -
                label: 'Trainers'
                icon: 'user'
                entity: 'Trainer'

            -
                label: 'Marketing & Wiki'

            -
                label: 'Marketing'
                icon: 'mail-bulk'
                entity: 'MarketingEvent'

            -
                label: 'Wiki: Training Term'
                route: 'wiki_organize_training_term'

            -
                icon: 'comment'
                entity: 'Feedback'

            -
                label: 'External Links'

            -
                label: 'Go to Homepage'
                icon: 'home'
                route: 'homepage'
